#!/bin/bash
# Make .desktop file and install it to /usr/share/appliations
# for all electron apps generated by https://github.com/jiahaog/nativefier in current folder
# app source dir name convention: {app-name}-linux-x64

gen_and_install_desktop() {
  rel_src_path=$1
  exec_name=$(echo $rel_src_path | grep -oP '\w+(-\w+)*(?=-linux)')
  app_name=$(echo $exec_name | sed 's/^./\U&/; s/-\(.\)/\U\1/g')
  abs_src_path=$(realpath $rel_src_path)
  sudo tee /usr/share/applications/${exec_name}.desktop > /dev/null << EOF
[Desktop Entry]
Type=Application
Name=$app_name
Comment=Electron App of $app_name
Exec=${abs_src_path}/${exec_name}
Icon=${abs_src_path}/resources/app/icon.png
Categories=Electron;Application;
Terminal=false
EOF
}

for dir in $(find . -maxdepth 1 -type d -not -path '.'); do
  gen_and_install_desktop $dir
done


