#!/bin/bash
is_linux () {
  [[ $('uname') == 'Linux' ]];
}

is_osx () {
  [[ $('uname') == 'Darwin' ]]
}

if is_osx; then
  pacman_install="brew install"
  # brew
  if [[ ! -f '/usr/local/bin/brew' ]]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  # vim
  which vim > /dev/null || $pacman_install vim
  # Tmux
  which tmux > /dev/null || $pacman_install tmux
  # ZSH
  which zsh > /dev/null || $pacman_install zsh
  # pip & Powerline
  BREW_PYTHON="/usr/local/bin/python"
  BREW_PIP="/usr/local/bin/pip"
  [[ -f $BREW_PYTHON ]] || $pacman_install python
  which pip > /dev/null || curl https://bootstrap.pypa.io/get-pip.py | $BREW_PYTHON
  $BREW_PIP install powerline-status
  $BREW_PIP install powerline-gitstatus
  # jq
  $pacman_install jq
  # colorls
  gem install colorls
  # fpp
  which fpp > /dev/null || $pacman_install fpp
  # urlview
  $pacman_install urlview
  # pyenv
  $pacman_install pyenv
  # rbenv
  $pacman_install rbenv

elif is_linux; then
  pacman_install="apt-get -y install"
  # folders
  [ -d ~/local/bin ] || mkdir -p ~/local/bin
  # sudo
  which sudo > /dev/null || $pacman_install sudo
  # vim
  which vim > /dev/null || sudo $pacman_install vim
  # curl
  which curl > /dev/null || sudo $pacman_install curl
  # ZSH
  which zsh > /dev/null || sudo $pacman_install zsh
  # Tmux
  which tmux > /dev/null || sudo $pacman_install tmux
  # pip & Powerline
  SYS_PYTHON="/usr/bin/python"
  SYS_PIP="/usr/bin/pip"
  [[ -f $SYS_PYTHON ]] || sudo $pacman_install python
  [[ -f $SYS_PIP ]] || sudo $pacman_install python-pip
  sudo $SYS_PIP install powerline-status
  sudo $SYS_PIP install powerline-gitstatus
  # jq
  sudo $pacman_install jq
  # Ruby && colorls
  sudo $pacman_install
  sudo gem install colorls
  # Keychain
  which keychain > /dev/null || sudo $pacman_install keychain
  # fpp
  git clone https://github.com/facebook/PathPicker.git ~/local/ && ln -s ~/local/PathPicker/fpp ~/local/bin/
  # urlview
  sudo apt-get -y install urlview
  # pyenv
  git clone https://github.com/pyenv/pyenv.git ~/.pyenv

  # rbenv & ruby-build
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

fi

# Oh-my-zsh
git clone https://github.com/15cm/oh-my-zsh.git ~/.oh-my-zsh

# z
git clone https://github.com/rupa/z.git ~/.z

# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# vim colors
wget -P ~/.vim/colors https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim

chsh -s $(which zsh)
